version: "3.7"
services:
  psql:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
      FACILITY_API_BASE_URL: http://manager
      TZ: 'UTC'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    command: postgres -c listen_addresses='*' -c log_statement=all -c log_destination=stderr
    ports:
      - "10233:5432"